
services:
  - type: web
    name: labl-iq-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: labl-iq-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REFRESH_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.vercel.app
      - key: PORT
        value: 8000

databases:
  - name: labl-iq-postgres
    databaseName: labl_iq_db
    user: labl_iq_user
    plan: starter
